### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by nightwulf1974** [qlcchain/WinQ-Android#1]
Special characters do not work, such as "$" or "%", etc.  Also, you cannot send Qlink tokens out of the wallet as you are not able to populate the address field as to where to send them.

**Comment by ariesunny** [comment]
Hi Hi, really sorry for no answer for so long time, Please try the latest WinQ version, it has been updated a lot during this period, I believe it has been fixed, Please let me know you have any issue on it, Thank you so much!!
