### ISSUE TITLE
Add in FIAT gateway to enable other crypto payment methods to the  WinQ wallet

### ISSUE THREAD

**Issue by taeyonlee** [qlcchain/WinQ-Android#14]
Since it finally comes to the time when WinQ wallet could function as standalone nep5 wallet. Is there any plan to integrate FIAT and other cryptocurrency gateway to the dApp? I see huge potential in involving more gateways for mass user adoption. WInQ itself is handy and stable, the team must work on its user acquisition as well for sustainable development.

**Comment by qlinkDev** [comment]
Eth neo eos and qlcchain wallets have been supported in recent releases。
