### ISSUE TITLE
Bug in Wallet/My Wifi & VPN Assets

### ISSUE THREAD

**Issue by namnhfreelancer** [qlcchain/WinQ-Android#18]
It not show all my assets. 
![image](https://user-images.githubusercontent.com/12831283/48135748-5ad84d00-e2d0-11e8-95de-02cb83f113d2.png)
When I choose Other
![image](https://user-images.githubusercontent.com/12831283/48135758-61ff5b00-e2d0-11e8-8864-1421c091e4d4.png)
My asset only show Canada
![image](https://user-images.githubusercontent.com/12831283/48135767-67f53c00-e2d0-11e8-8261-e16aab391bf6.png)
When i choose USA
![image](https://user-images.githubusercontent.com/12831283/48135774-6d528680-e2d0-11e8-9933-8f6a7f498f6d.png)
My asset show my USA VPN Assets.

So i think in "My Wifi & VPN Assets" tab, It need show all assets all time.

**Comment by namnhfreelancer** [comment]
@gythialy @JellyFoo @kuangzihui @zhanglang108

**Comment by playblockz** [comment]
It has been modified in the new version。
