### ISSUE TITLE
App doesn't start on Android 7.1.1, Nexus 6

### ISSUE THREAD

**Issue by flojdek** [qlcchain/WinQ-Android#4]
Hey, I've installed the app (1.0.6 13.02.2018) on my Nexus 6, Android 7.1.1 but it doesn't start. I can see the welcome screen, but it's constantly loading without any progress.

Would be great to know which Android versions are supported by the app.

PS. I'll provide more debug details when I have more time.

**Comment by ariesunny** [comment]
Hi Hi, Sorry for no answer for so long time, Please try the latest WinQ version, it has been updated a lot during this period, and it is ready on Google Play Store, Please let me know you have any issue on it, Thank you so much!!
